from fastapi import APIRouter
from app.routers import health, trades, dhan, dhan_webhook, capital_events, accounts, capital_dashboard, coach, setup_playbook, export, analytics, trade_ideas, daily_journal, auth, ai_settings, tier_config, broker_import, risk_dashboard, trade_timeline, partial_exit, emotion_log, execution_grade, lifecycle_analytics

api_router = APIRouter(prefix="/api/v1")
api_router.include_router(auth.router, tags=["auth"])
api_router.include_router(health.router, prefix="/health", tags=["health"])
api_router.include_router(broker_import.router, prefix="/trades", tags=["broker-import"])
api_router.include_router(trades.router, tags=["trades"])
api_router.include_router(trade_timeline.router, tags=["trade-timeline"])
api_router.include_router(partial_exit.router, tags=["partial-exits"])
api_router.include_router(emotion_log.router, tags=["emotion-logs"])
api_router.include_router(execution_grade.router, tags=["execution-grades"])
api_router.include_router(dhan.router, tags=["dhan-sync"])
api_router.include_router(dhan_webhook.router, tags=["dhan-webhook"])
api_router.include_router(capital_events.router, tags=["capital-events"])
api_router.include_router(capital_dashboard.router, tags=["capital-dashboard"])
api_router.include_router(accounts.router, tags=["accounts"])
api_router.include_router(risk_dashboard.router, tags=["risk-dashboard"])
api_router.include_router(coach.router, tags=["ai-coach"])
api_router.include_router(setup_playbook.router, tags=["setup-playbook"])
api_router.include_router(export.router, tags=["export"])
api_router.include_router(analytics.router, tags=["analytics"])
api_router.include_router(trade_ideas.router, tags=["trade-ideas"])
api_router.include_router(daily_journal.router, tags=["daily-journal"])
api_router.include_router(ai_settings.router, tags=["ai-settings"])
api_router.include_router(tier_config.router, tags=["tier-config"])
api_router.include_router(lifecycle_analytics.router, tags=["lifecycle-analytics"])
