export const newUiTokens = {
  color: {
    bg: '#050711',
    bgSoft: '#080b16',
    canvas: '#0b1020',
    surface: '#101827',
    surfaceElevated: '#151f32',
    surfaceMuted: '#0d1422',
    border: 'rgba(148, 163, 184, 0.16)',
    borderStrong: 'rgba(148, 163, 184, 0.28)',
    textPrimary: '#f8fafc',
    textSecondary: '#cbd5e1',
    textMuted: '#7f8da3',
    accent: '#7c8cff',
    accentStrong: '#a78bfa',
    profit: '#34d399',
    loss: '#fb7185',
    warning: '#fbbf24',
    info: '#38bdf8',
    neutral: '#94a3b8',
    focusRing: 'rgba(124, 140, 255, 0.42)',
  },
  effect: {
    shadowSubtle: 'var(--tj-shadow-subtle)',
    shadowElevated: 'var(--tj-shadow-elevated)',
    glowAccent: 'var(--tj-glow-accent)',
    glowWarning: 'var(--tj-glow-warning)',
    backdrop: 'var(--tj-backdrop)',
  },
  radius: {
    small: 'var(--tj-radius-sm)',
    medium: 'var(--tj-radius-md)',
    large: 'var(--tj-radius-lg)',
    panel: 'var(--tj-radius-panel)',
    full: 'var(--tj-radius-full)',
  },
  spacing: {
    pageX: 'var(--tj-space-page-x)',
    pageY: 'var(--tj-space-page-y)',
    section: 'var(--tj-space-section)',
    panel: 'var(--tj-space-panel)',
    card: 'var(--tj-space-card)',
    row: 'var(--tj-space-row)',
    controlX: 'var(--tj-space-control-x)',
    controlY: 'var(--tj-space-control-y)',
  },
  typography: {
    hero: 'var(--tj-text-hero)',
    pageTitle: 'var(--tj-text-page-title)',
    panelTitle: 'var(--tj-text-panel-title)',
    kpiPrimary: 'var(--tj-text-kpi-primary)',
    kpiSecondary: 'var(--tj-text-kpi-secondary)',
    body: 'var(--tj-text-body)',
    caption: 'var(--tj-text-caption)',
    micro: 'var(--tj-text-micro)',
    numeric: 'var(--tj-font-numeric)',
  },
  layout: {
    contentMax: 'var(--tj-content-max)',
    sidebarWidth: 'var(--tj-sidebar-w)',
    drawerWidth: 'var(--tj-drawer-w)',
    mobileBottomNavHeight: 'var(--tj-mobile-bottom-nav-h)',
  },
  motion: {
    fast: 'var(--tj-transition-fast)',
    normal: 'var(--tj-transition-normal)',
    easing: 'var(--tj-ease-standard)',
  },
} as const

export type NewUiTokens = typeof newUiTokens
